## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
arr = np.random.randint(1, 11, size=10)
mask = (arr >=3) & (arr <=8)
arr [mask] *= -1
arr

array([-8, -7, -4, -3, -5, -7,  2, -6,  2, -6])

**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
arr = np.random.randint(1, 11, size=10)
print (arr)
max_index = np.argmax(arr)
print (max_index)
arr[max_index] = 0
print (arr)

[10  4  1  4  2  7  6  3  3  9]
0
[0 4 1 4 2 7 6 3 3 9]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
arr1 = np.arange (1,9).reshape (2, 4)
arr2 = np.arange(1,9).reshape(4, 2)
result = np.dot(arr1, arr2)
print (result)

[[ 50  60]
 [114 140]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
A = np.random.randint(1, 10, (8, 3))
B = np.random.randint(1, 10, (2, 2))
B_sets = [set(row) for row in B]
matching_rows = []
for idx, a_row in enumerate(A):
    A_sets = set(a_row) 
    if all(b_set.issubset(A_sets) for b_set in B_sets):
        matching_rows.append(idx)
print(matching_rows)

[]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
A = np.array([[1, 2, 3],[2, 2, 2], [3, 3, 3],[4, 5, 6],[7, 7, 7], [1, 1, 1],[8, 9, 0], [5, 5, 5], [0, 0, 0], [2, 3, 4]  
])
mask = ((A[:, 0] == A[:, 1]) & (A[:, 1] == A[:, 2]))
result = A[mask]
print(result)

[[2 2 2]
 [3 3 3]
 [7 7 7]
 [1 1 1]
 [5 5 5]
 [0 0 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
array = np.random.randint(1, 10, (8, 3))
unique_array = np.unique(array, axis=0)
print (unique_array)

[[1 1 3]
 [2 2 1]
 [3 1 4]
 [3 1 9]
 [4 9 5]
 [5 6 2]
 [7 2 4]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [9]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) 
diagonal_product = np.prod(np.diag(X)[np.diag(X)!=0])
print (diagonal_product)


X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) 
product = 1
min_dim = min(X.shape)
for i in range(min_dim):
    if X[i, i] != 0: 
        product *= X[i, i]
print(product)



3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [10]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
x = np.sort(x)
y = np.sort(y)
array_equal = np.array_equal(x, y)
print(array_equal)


from collections import Counter
def multisets_equal_counter(x, y):
    return Counter(x) == Counter(y)
print(multisets_equal_counter(x, y))


True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [11]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero = x==0
print (x[1:][zero[:-1]].max())

max_value = max((x[i] for i in range(1, len(x)) if x[i-1] == 0))
print(max_value)


5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [12]:
x = np.array([2, 2, 2, 3, 3, 3, 5])
print(np.unique(x, return_counts=True))

def rle_encode_numpy(X):
    return np.unique(X, return_counts=True)
values, lengths = rle_encode_numpy(x)
print(values, lengths)

(array([2, 3, 5]), array([3, 3, 1]))
[2 3 5] [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [33]:
from scipy.spatial.distance import cdist
import time

X = np.random.rand(100, 50)
Y = np.random.rand(150, 50)   
start_time = time.time()
dist_manual = euclidean_distance_matrix(X, Y)
end_time = time.time()
time_manual = end_time - start_time
print(time_manual)

start_time = time.time()
dist_scipy = cdist(X, Y, metric='euclidean')
end_time = time.time()
time_scipy = end_time - start_time
print(time_scipy)

0.0070002079010009766
0.0009999275207519531


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [48]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [53]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats 

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [55]:
crunchiemunchies_calories = 60
competitor_calories = np.mean(calorie_stats)
average_calories = competitor_calories - crunchiemunchies_calories
print("Среднее количество калорий у конкурентов выше на:", average_calories)

Среднее количество калорий у конкурентов выше на: 46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [62]:
calorie_stats_sorted = np.sort (calorie_stats)
print (competitor_calories)
print (calorie_stats_sorted)

106.88311688311688
[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [64]:
median_calories = np.median (calorie_stats)
print (median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [75]:
percentile = np.percentile(calorie_stats, [25, 50, 75])
print (percentile)
nth_percentile = percentile[percentile > 60][0] 
print (nth_percentile)

[100. 110. 110.]
100.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [80]:
sum_calor = calorie_stats.sum()
cal_60 = np.sum ([calorie_stats > 60])
more_calories = cal_60/sum_calor * 100
print (more_calories)

0.8991494532199271


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [82]:
calorie_std = np.std (calorie_stats)
print (calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [87]:
print ("1) CrunchieMunchies содержит 60 калорий на порцию, что на 46,88 калорий меньше, чем среднее значение у конкурентов. Это показывает нам значительное преимущество CrunchieMunchies в вопросе низкой калорийности продукта.")
print ("2) Большинство значений калорий у конкурентов намного выше среднего, а это значит, что значительная часть продукции этих брендов имеет высокую калорийность.")
print ("3) Результат стандартного отклонения равный 19, говорит нам о высокой степени разброса данных или их неоднородности.")
print ("4) Данные выводы позволяют нам выделить бренд CrunchieMunchies как более здоровый и подходящий выбор для потребителей, заботящихся о своем рационе.")

1) CrunchieMunchies содержит 60 калорий на порцию, что на 46,88 калорий меньше, чем среднее значение у конкурентов. Это показывает нам значительное преимущество CrunchieMunchies в вопросе низкой калорийности продукта.
2) Большинство значений калорий у конкурентов намного выше среднего, а это значит, что значительная часть продукции этих брендов имеет высокую калорийность.
3) Результат стандартного отклонения равный 19, говорит нам о высокой степени разброса данных или их неоднородности.
4) Данные выводы позволяют нам выделить бренд CrunchieMunchies как более здоровый и подходящий выбор для потребителей, заботящихся о своем рационе.
